// Curated list of well-known, real travel quotes with correct attribution —
// hardcoded client-side (no API), used by TravelQuoteWidget on Home.
export type TravelQuote = {
  quote: string;
  author: string;
};

export const TRAVEL_QUOTES: TravelQuote[] = [
  { quote: "The world is a book, and those who do not travel read only one page.", author: "Saint Augustine" },
  { quote: "Travel is fatal to prejudice, bigotry, and narrow-mindedness.", author: "Mark Twain" },
  { quote: "Not all those who wander are lost.", author: "J.R.R. Tolkien" },
  { quote: "To travel is to live.", author: "Hans Christian Andersen" },
  { quote: "Once a year, go someplace you've never been before.", author: "Dalai Lama" },
  { quote: "Travel makes one modest. You see what a tiny place you occupy in the world.", author: "Gustave Flaubert" },
  { quote: "I have found out that there ain't no surer way to find out whether you like people or hate them than to travel with them.", author: "Mark Twain" },
  { quote: "We travel, some of us forever, to seek other states, other lives, other souls.", author: "Anaïs Nin" },
  { quote: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { quote: "The real voyage of discovery consists not in seeking new landscapes, but in having new eyes.", author: "Marcel Proust" },
  { quote: "Traveling – it leaves you speechless, then turns you into a storyteller.", author: "Ibn Battuta" },
  { quote: "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.", author: "Mark Twain" },
  { quote: "It is not down on any map; true places never are.", author: "Herman Melville" },
  { quote: "Wherever you go becomes a part of you somehow.", author: "Anita Desai" },
  { quote: "A good traveler has no fixed plans and is not intent on arriving.", author: "Lao Tzu" },
  { quote: "There are no foreign lands. It is the traveler only who is foreign.", author: "Robert Louis Stevenson" },
  { quote: "For my part, I travel not to go anywhere, but to go. I travel for travel's sake.", author: "Robert Louis Stevenson" },
  { quote: "The gladdest moment in human life is a departure into unknown lands.", author: "Sir Richard Burton" },
  { quote: "Travel is more than seeing sights; it is a change that goes on, deep and permanent, in the ideas of living.", author: "Miriam Beard" },
  { quote: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
  { quote: "Adventure is worthwhile in itself.", author: "Amelia Earhart" },
  { quote: "The use of traveling is to regulate imagination by reality, and instead of thinking how things may be, to see them as they are.", author: "Samuel Johnson" },
  { quote: "Travel and change of place impart new vigor to the mind.", author: "Seneca" },
  { quote: "To awaken quite alone in a strange town is one of the pleasantest sensations in the world.", author: "Freya Stark" },
  { quote: "I am not the same having seen the moon shine on the other side of the world.", author: "Mary Anne Radmacher" },
  { quote: "Travel far enough, you meet yourself.", author: "David Mitchell" },
  { quote: "Live your life by a compass, not a clock.", author: "Stephen Covey" },
  { quote: "Take only memories, leave only footprints.", author: "Chief Seattle" },
  { quote: "A traveler without observation is a bird without wings.", author: "Moslih Eddin Saadi" },
  { quote: "Don't listen to what they say. Go see.", author: "Chinese Proverb" },
  { quote: "Travel is the only thing you buy that makes you richer.", author: "Anonymous" },
  { quote: "One's destination is never a place, but a new way of seeing things.", author: "Henry Miller" },
  { quote: "I have never in my life learned anything from any man who agreed with me.", author: "Dudley Field Malone" },
  { quote: "Jobs fill your pocket, but adventures fill your soul.", author: "Jaime Lyn Beatty" },
  { quote: "To my mind, the greatest reward and luxury of travel is to be able to experience everyday things as if for the first time.", author: "Bill Bryson" },
  { quote: "The world is full of magical things patiently waiting for our wits to grow sharper.", author: "Bertrand Russell" },
  { quote: "In every walk with nature, one receives far more than he seeks.", author: "John Muir" },
  { quote: "The mountains are calling and I must go.", author: "John Muir" },
  { quote: "Wandering re-establishes the original harmony which once existed between man and the universe.", author: "Anatole France" },
  { quote: "It feels good to be lost in the right direction.", author: "Rumi" },
  { quote: "Travel is never a matter of money but of courage.", author: "Paulo Coelho" },
  { quote: "The biggest adventure you can take is to live the life of your dreams.", author: "Oprah Winfrey" },
  { quote: "We wander for distraction, but we travel for fulfillment.", author: "Hilaire Belloc" },
  { quote: "Of all the books in the world, the best stories are found between the pages of a passport.", author: "Anonymous" },
  { quote: "Travel is glamorous only in retrospect.", author: "Paul Theroux" },
  { quote: "Tourists don't know where they've been, travelers don't know where they're going.", author: "Paul Theroux" },
  { quote: "Extensive traveling induces a feeling of encapsulation; and travel, so broadening at first, contracts the mind.", author: "Paul Theroux" },
  { quote: "A journey is best measured in friends, rather than miles.", author: "Tim Cahill" },
  { quote: "Nobody can discover the world for somebody else. Only when we discover it for ourselves does it become common ground.", author: "Wendell Berry" },
  { quote: "The world is big and I want to have a good look at it before it gets dark.", author: "John Muir" },
  { quote: "Half the fun of travel is the aesthetic of lostness.", author: "Ray Bradbury" },
  { quote: "Better to see something once than to hear about it a thousand times.", author: "Asian Proverb" },
  { quote: "To be a good traveler you must be able to relinquish all sense of demand that the place provide you with anything.", author: "Freya Stark" },
  { quote: "Travelling is almost like talking with men of other centuries.", author: "René Descartes" },
  { quote: "Great things are done when men and mountains meet.", author: "William Blake" },
  { quote: "It is good to have an end to journey toward; but it is the journey that matters, in the end.", author: "Ursula K. Le Guin" },
  { quote: "The journey not the arrival matters.", author: "T.S. Eliot" },
  { quote: "One trip can change your outlook, your opinions, or your entire life.", author: "Rick Steves" },
  { quote: "Two roads diverged in a wood, and I—I took the one less traveled by, and that has made all the difference.", author: "Robert Frost" },
  { quote: "Not until we are lost do we begin to understand ourselves.", author: "Henry David Thoreau" },
  { quote: "I went to the woods because I wished to live deliberately.", author: "Henry David Thoreau" },
  { quote: "All journeys have secret destinations of which the traveler is unaware.", author: "Martin Buber" },
  { quote: "Journey is the destination.", author: "Dan Eldon" },
  { quote: "A ship in harbor is safe, but that is not what ships are built for.", author: "John A. Shedd" },
  { quote: "The map of the world is fashioned by the sum of every human footstep.", author: "Cesare Pavese" },
  { quote: "Traveling is a brutality. It forces you to trust strangers and to lose sight of all that familiar comfort of home and friends.", author: "Cesare Pavese" },
  { quote: "Travel isn't always pretty. It isn't always comfortable. Sometimes it hurts, it even breaks your heart. But that's okay. The journey changes you.", author: "Anthony Bourdain" },
  { quote: "You learn more about a country from listening than from talking.", author: "Anthony Bourdain" },
  { quote: "As you get older, you realize sooner is better than later, because life goes fast.", author: "Anthony Bourdain" },
  { quote: "Nothing behind me, everything ahead of me, as is ever so on the road.", author: "Jack Kerouac" },
  { quote: "The only people for me are the mad ones, the ones who are mad to live, mad to talk, mad to be saved.", author: "Jack Kerouac" },
  { quote: "The soul that sees beauty may sometimes walk alone.", author: "Johann Wolfgang von Goethe" },
  { quote: "The traveler sees what he sees, the tourist sees what he has come to see.", author: "G.K. Chesterton" },
  { quote: "The traveler was active; he went strenuously in search of adventure. The tourist is passive; he expects interesting things to happen to him.", author: "Daniel J. Boorstin" },
  { quote: "In wisdom gathered over time I have found that every experience is a form of exploration.", author: "Ansel Adams" },
  { quote: "There is a kind of magicness about going far away and then coming back all changed.", author: "Kate Douglas Wiggin" },
  { quote: "To wander is to be alive.", author: "Roman Payne" },
  { quote: "It is only through adventure that some people can realize their full potential.", author: "Sir Edmund Hillary" },
  { quote: "Somewhere between the sunrise and the sunset, there's your life.", author: "Pico Iyer" },
  { quote: "We travel not to escape life, but for life not to escape us.", author: "Anonymous" },
  { quote: "The pleasure we derive from journeys is perhaps dependent more on the mindset with which we travel than on the destination we travel to.", author: "Alain de Botton" },
  { quote: "Wherever I go, I go with all my heart.", author: "Confucius" },
  { quote: "He who does not travel does not know the value of men.", author: "Moorish Proverb" },
  { quote: "There are two kinds of travel: first class, and with children.", author: "Robert Benchley" },
  { quote: "Travel teaches toleration.", author: "Benjamin Disraeli" },
  { quote: "He that travels much knows much.", author: "Thomas Fuller" },
  { quote: "I never travel without my diary. One should always have something sensational to read in the train.", author: "Oscar Wilde" },
  { quote: "Traveling is the ruin of all happiness! There's no looking at a building after seeing Italy.", author: "Fanny Burney" },
  { quote: "Give me the clear blue sky over my head, and the green turf beneath my feet, a winding road before me, and a three hours' march to dinner.", author: "William Hazlitt" },
  { quote: "He who would travel happily must travel light.", author: "Antoine de Saint-Exupéry" },
  { quote: "It is not worth the ink or the trouble to write to your friends whom you dearly love and never see, if you have nothing to tell them but that you are well, and hope they are the same.", author: "Mark Twain" },
  { quote: "Around here, however, we don't look backwards for very long. We keep moving forward, opening up new doors and doing new things.", author: "Walt Disney" },
  { quote: "Climb the mountains and get their good tidings.", author: "John Muir" },
  { quote: "The mind, once expanded to the dimensions of larger ideas, never returns to its original size.", author: "Oliver Wendell Holmes" },
  { quote: "Perhaps travel cannot prevent bigotry, but by demonstrating that all peoples cry, laugh, eat, worry, and die, it can introduce the idea that if we try and understand each other, we may even become friends.", author: "Maya Angelou" },
  { quote: "I long, as does every human being, to be at home wherever I find myself.", author: "Maya Angelou" },
  { quote: "The soul of a journey is liberty, perfect liberty, to think, feel, do just as one pleases.", author: "William Hazlitt" },
  { quote: "A wise traveler never despises his own country.", author: "William Hazlitt" },
  { quote: "Little journeys to the homes of great teachers.", author: "Elbert Hubbard" },
  { quote: "No one realizes how beautiful it is to travel until he comes home and rests his head on his old, familiar pillow.", author: "Lin Yutang" },
  { quote: "A great step towards independence is a good-humored stomach.", author: "Lin Yutang" },
  { quote: "The gladdest thing in the world is to go on a journey.", author: "Christina Rossetti" },
  { quote: "Travel is the frivolous part of serious lives, and the serious part of frivolous ones.", author: "Anne Sophie Swetchine" },
  { quote: "See the world. It's more fantastic than any dream made or paid for in factories.", author: "Ray Bradbury" },
];
